### ISSUE TITLE
[Guide] node-irsdk with vuejs + electron-builder

### ISSUE THREAD

**Issue by hmiefert** [apihlaja/node-irsdk#96]
Hi guys,

it took some time for me to figure out how to create a vuejs based electron app with node-irsdk support. I hope it's ok to leave a step by step guide here, even though it's not an issue. I wasn't sure where to put it else and thought maybe it's worth the write.

`npm install -g @vue/cli`

`vue create myapp`

cd into your app

`vue add electron-builder`
Latest version as of writing is electron 11

`npm install --save https://github.com/sabifa/node-irsdk`
I selected this fork, as it already fixed the import of the compiled source. If there is any better out there, let me know.

`npm install --save-dev electron-rebuild`

`.\node-modules\.bin\electron-rebuild.cmd`
This will rebuild the node-irsdk to be compatible with the electron version you selected - at least on windows.

Add a vue.config.js file to your project root with the following content
```
module.exports = {
    pluginOptions: {
        electronBuilder: {
            externals: ['node-irsdk'],
            nodeIntegration: true
        }
    }
}
```
This was the most crucial part to figure out - at least for me.

Now you can run your node-irsdk code in background.js as you would in every other electron app.
```
....
import * as irsdk from 'node-irsdk'
....
const iracing = irsdk.init({telemetryUpdateInterval: 500, sessionInfoUpdateInterval: 2000})
iracing.on('Connected', function() {
  console.log('iRacing connected..')
})
iracing.on('Disconnected', function() {
  console.log('iRacing disconnected..')
})
```

*edit: as this is way outdated and as of 30/12/2022 I couldn't get a solution with existing forks, I tried to come up with my own solution. So, if you want to give it a try, you can find it [here](https://github.com/hmiefert/node-irsdk-2023).

**Comment by sabifa** [comment]
Great idea to post it here so it's easier for others to create their first project using this package!

I am using the exact same method you described and it's been working totally fine for almost a year now! I had to enable nodeIntegration though, which could be caused by another dependency.

**Comment by hmiefert** [comment]
If you don't mind me asking: how do you get the telemetry data to the frontend?
Would you recommend using a websocket-server?

**Comment by sabifa** [comment]
Sure! I'm using the IPC communication approach.

It looks like this:
```ts
// background.ts
const setupIrSdk = (): void => {
    const irsdk = require('node-irsdk');

    irsdk.init({
      telemetryUpdateInterval: 17,
      sessionInfoUpdateInterval: 17,
    });

    const iRacing = irsdk.getInstance();

    iRacing.on('Connected', () => {
      win?.webContents.send('ir_connected');
    });

    iRacing.on('Telemetry', (data: unknown) => {
      win?.webContents.send('ir_telemetry', data);
    });

    iRacing.on('SessionInfo', (data: unknown) => {
      win?.webContents.send('ir_sessionInfo', data);
    });

    iRacing.on('Disconnected', () => {
      win?.webContents.send('ir_disconnected');
    });
  };
```

In order to not miss any information while the renderer process first load make sure to call this method after the vue.js process has loaded successfully. My approach for this is to send an event from within the App's created method to the main process like so:

Also take a look at `listenOnIpcForIrEvents` where I listen for the events from the main process 😅 

```ts

<script lang="ts">
import Vue from 'vue';

const ipc = require('electron').ipcRenderer;

export default Vue.extend({
  name: 'App',
  created() {
    this.listenOnIpcForIrEvents();

    ipc.send('app_loaded');
  },
  methods: {
    listenOnIpcForIrEvents(): void {
      ipc.on('ir_connected', () => handleConnected());
      ipc.on('ir_telemetry', (event, args: { values: import('node-irsdk').TelemetryEventValues }) => handleTelemetry(args.values));
      ipc.on('ir_sessionInfo', (event, args: { data: import('node-irsdk').SessionInfoEventData }) => handleSessionInfo(args.data));
      ipc.on('ir_disconnected', () => handleDisconnected());
    },
  },
});
</script>
```

Finally in your `background.(ts/js)` call:

```ts
ipcMain.on('app_loaded', () => {
    setupIrSdk();
});
```

And voilà you should be good to go 🚀

**Comment by hmiefert** [comment]
@sabifa Thanks, I only read about IPC, haven't tried it myself though. Your code is a great starting point for me, appreciate it!

**Comment by hmiefert** [comment]
> I had to enable nodeIntegration though, which could be caused by another dependency.

Yep, this is a must. Otherwise I got an error in the frontend: __dirname is not defined

**Comment by martinguder** [comment]
Hi. Thanks for the Tutorial. Back then I was successfully building the electron based irsdk with some info from some users like @sabifa and @heimdallexus ... but recently our started to build the code again and I get a lot of weird errors. Probably bc of the fact, that I have updated node meanwhile and the rebuild does not work anymore. Also tried your tutorial, as I thought it's working better, but not a chance. Here my error-log I got by installing sabifa's version into a new project (prior installed latest electron and electron-build) here as well.

`0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\Martin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '--save',
0 verbose cli   'https://github.com/sabifa/node-irsdk'
0 verbose cli ]
1 info using npm@7.5.3
2 info using node@v17.0.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Users\Martin\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:C:\Users\Martin\Documents\GitHub\motorista\.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:C:\Users\Martin\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\Martin\AppData\Roaming\npm\etc\npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session dc4f42b786548585
20 timing npm:load Completed in 14ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree:init Completed in 114ms
23 timing idealTree:userRequests Completed in 1662ms
24 silly idealTree buildDeps
25 silly fetch manifest node-irsdk@https://github.com/sabifa/node-irsdk
26 silly placeDep ROOT node-irsdk@2.1.6 OK for: motorista@0.0.1 want: https://github.com/sabifa/node-irsdk
27 silly fetch manifest js-yaml@3.*
28 silly fetch manifest nan@2.14.0
29 silly fetch manifest prebuild-install@^5.0.0
30 http fetch GET 200 https://registry.npmjs.org/js-yaml 87ms (from cache)
31 http fetch GET 200 https://registry.npmjs.org/prebuild-install 89ms (from cache)
32 http fetch GET 304 https://registry.npmjs.org/nan 163ms (from cache)
33 timing idealTree:#root Completed in 1433ms
34 silly placeDep node_modules/node-irsdk js-yaml@3.14.1 OK for: node-irsdk@2.1.6 want: 3.*
35 silly placeDep ROOT nan@2.14.0 OK for: node-irsdk@2.1.6 want: 2.14.0
36 silly placeDep ROOT prebuild-install@5.3.6 OK for: node-irsdk@2.1.6 want: ^5.0.0
37 silly fetch manifest argparse@^1.0.7
38 silly fetch manifest esprima@^4.0.0
39 silly fetch manifest expand-template@^2.0.3
40 silly fetch manifest github-from-package@0.0.0
41 silly fetch manifest mkdirp-classic@^0.5.3
42 silly fetch manifest napi-build-utils@^1.0.1
43 silly fetch manifest noop-logger@^0.1.1
44 silly fetch manifest simple-get@^3.0.3
45 silly fetch manifest tar-fs@^2.0.0
46 silly fetch manifest tunnel-agent@^0.6.0
47 silly fetch manifest which-pm-runs@^1.0.0
48 http fetch GET 200 https://registry.npmjs.org/argparse 16ms (from cache)
49 http fetch GET 200 https://registry.npmjs.org/esprima 16ms (from cache)
50 http fetch GET 200 https://registry.npmjs.org/expand-template 16ms (from cache)
51 http fetch GET 200 https://registry.npmjs.org/noop-logger 15ms (from cache)
52 http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 17ms (from cache)
53 http fetch GET 200 https://registry.npmjs.org/github-from-package 18ms (from cache)
54 http fetch GET 200 https://registry.npmjs.org/which-pm-runs 17ms (from cache)
55 http fetch GET 200 https://registry.npmjs.org/tar-fs 18ms (from cache)
56 http fetch GET 200 https://registry.npmjs.org/simple-get 19ms (from cache)
57 http fetch GET 200 https://registry.npmjs.org/napi-build-utils 19ms (from cache)
58 http fetch GET 200 https://registry.npmjs.org/tunnel-agent 19ms (from cache)
59 timing idealTree:node_modules/node-irsdk Completed in 28ms
60 timing idealTree:node_modules/nan Completed in 0ms
61 silly placeDep ROOT expand-template@2.0.3 OK for: prebuild-install@5.3.6 want: ^2.0.3
62 silly placeDep ROOT github-from-package@0.0.0 OK for: prebuild-install@5.3.6 want: 0.0.0
63 silly placeDep ROOT mkdirp-classic@0.5.3 OK for: prebuild-install@5.3.6 want: ^0.5.3
64 silly placeDep ROOT napi-build-utils@1.0.2 OK for: prebuild-install@5.3.6 want: ^1.0.1
65 silly placeDep ROOT noop-logger@0.1.1 OK for: prebuild-install@5.3.6 want: ^0.1.1
66 silly placeDep ROOT simple-get@3.1.0 OK for: prebuild-install@5.3.6 want: ^3.0.3
67 silly placeDep ROOT tar-fs@2.1.1 OK for: prebuild-install@5.3.6 want: ^2.0.0
68 silly placeDep ROOT tunnel-agent@0.6.0 OK for: prebuild-install@5.3.6 want: ^0.6.0
69 silly placeDep ROOT which-pm-runs@1.0.0 OK for: prebuild-install@5.3.6 want: ^1.0.0
70 silly fetch manifest decompress-response@^4.2.0
71 silly fetch manifest simple-concat@^1.0.0
72 silly fetch manifest chownr@^1.1.1
73 silly fetch manifest tar-stream@^2.1.4
74 http fetch GET 200 https://registry.npmjs.org/decompress-response 6ms (from cache)
75 http fetch GET 200 https://registry.npmjs.org/simple-concat 7ms (from cache)
76 http fetch GET 200 https://registry.npmjs.org/tar-stream 6ms (from cache)
77 http fetch GET 304 https://registry.npmjs.org/chownr 58ms (from cache)
78 timing idealTree:node_modules/prebuild-install Completed in 65ms
79 timing idealTree:node_modules/expand-template Completed in 0ms
80 timing idealTree:node_modules/github-from-package Completed in 0ms
81 timing idealTree:node_modules/mkdirp-classic Completed in 0ms
82 timing idealTree:node_modules/napi-build-utils Completed in 0ms
83 timing idealTree:node_modules/noop-logger Completed in 0ms
84 silly placeDep node_modules/simple-get decompress-response@4.2.1 OK for: simple-get@3.1.0 want: ^4.2.0
85 silly placeDep ROOT simple-concat@1.0.1 OK for: simple-get@3.1.0 want: ^1.0.0
86 silly fetch manifest mimic-response@^2.0.0
87 http fetch GET 200 https://registry.npmjs.org/mimic-response 3ms (from cache)
88 timing idealTree:node_modules/simple-get Completed in 5ms
89 timing idealTree:node_modules/simple-concat Completed in 0ms
90 silly placeDep node_modules/tar-fs chownr@1.1.4 OK for: tar-fs@2.1.1 want: ^1.1.1
91 silly placeDep ROOT tar-stream@2.2.0 OK for: tar-fs@2.1.1 want: ^2.1.4
92 silly fetch manifest fs-constants@^1.0.0
93 silly fetch manifest readable-stream@^3.1.1
94 http fetch GET 200 https://registry.npmjs.org/fs-constants 4ms (from cache)
95 http fetch GET 200 https://registry.npmjs.org/readable-stream 3ms (from cache)
96 timing idealTree:node_modules/tar-fs Completed in 6ms
97 silly placeDep ROOT fs-constants@1.0.0 OK for: tar-stream@2.2.0 want: ^1.0.0
98 silly placeDep node_modules/tar-stream readable-stream@3.6.0 OK for: tar-stream@2.2.0 want: ^3.1.1
99 timing idealTree:node_modules/tar-stream Completed in 1ms
100 timing idealTree:node_modules/fs-constants Completed in 0ms
101 timing idealTree:node_modules/tunnel-agent Completed in 0ms
102 timing idealTree:node_modules/which-pm-runs Completed in 0ms
103 silly placeDep node_modules/node-irsdk argparse@1.0.10 OK for: js-yaml@3.14.1 want: ^1.0.7
104 silly placeDep ROOT esprima@4.0.1 OK for: js-yaml@3.14.1 want: ^4.0.0
105 silly fetch manifest sprintf-js@~1.0.2
106 http fetch GET 200 https://registry.npmjs.org/sprintf-js 1ms (from cache)
107 timing idealTree:node_modules/node-irsdk/node_modules/js-yaml Completed in 4ms
108 timing idealTree:node_modules/esprima Completed in 0ms
109 silly placeDep node_modules/node-irsdk sprintf-js@1.0.3 OK for: argparse@1.0.10 want: ~1.0.2
110 timing idealTree:node_modules/node-irsdk/node_modules/argparse Completed in 1ms
111 timing idealTree:node_modules/node-irsdk/node_modules/sprintf-js Completed in 0ms
112 silly placeDep node_modules/simple-get mimic-response@2.1.0 OK for: decompress-response@4.2.1 want: ^2.0.0
113 timing idealTree:node_modules/simple-get/node_modules/decompress-response Completed in 0ms
114 timing idealTree:node_modules/simple-get/node_modules/mimic-response Completed in 0ms
115 timing idealTree:node_modules/tar-fs/node_modules/chownr Completed in 0ms
116 timing idealTree:node_modules/tar-stream/node_modules/readable-stream Completed in 0ms
117 timing idealTree:buildDeps Completed in 1545ms
118 timing idealTree:fixDepFlags Completed in 2ms
119 timing idealTree Completed in 3330ms
120 timing reify:loadTrees Completed in 3330ms
121 timing reify:diffTrees Completed in 10ms
122 silly reify moves {}
123 timing reify:retireShallow Completed in 1ms
124 timing reify:createSparse Completed in 5ms
125 timing reify:loadBundles Completed in 0ms
126 timing reifyNode:node_modules/which-pm-runs Completed in 55ms
127 timing reifyNode:node_modules/tar-fs/node_modules/chownr Completed in 55ms
128 timing reifyNode:node_modules/simple-get Completed in 55ms
129 timing reifyNode:node_modules/mkdirp-classic Completed in 56ms
130 timing reifyNode:node_modules/fs-constants Completed in 56ms
131 timing reifyNode:node_modules/tunnel-agent Completed in 57ms
132 timing reifyNode:node_modules/simple-get/node_modules/mimic-response Completed in 57ms
133 timing reifyNode:node_modules/simple-get/node_modules/decompress-response Completed in 57ms
134 timing reifyNode:node_modules/expand-template Completed in 61ms
135 timing reifyNode:node_modules/simple-concat Completed in 62ms
136 timing reifyNode:node_modules/napi-build-utils Completed in 62ms
137 timing reifyNode:node_modules/noop-logger Completed in 65ms
138 timing reifyNode:node_modules/tar-stream Completed in 65ms
139 timing reifyNode:node_modules/github-from-package Completed in 68ms
140 timing reifyNode:node_modules/prebuild-install Completed in 72ms
141 timing reifyNode:node_modules/node-irsdk/node_modules/sprintf-js Completed in 74ms
142 timing reifyNode:node_modules/esprima Completed in 76ms
143 timing reifyNode:node_modules/tar-stream/node_modules/readable-stream Completed in 80ms
144 timing reifyNode:node_modules/node-irsdk/node_modules/argparse Completed in 84ms
145 timing reifyNode:node_modules/tar-fs Completed in 84ms
146 timing reifyNode:node_modules/node-irsdk/node_modules/js-yaml Completed in 91ms
147 timing reifyNode:node_modules/nan Completed in 93ms
148 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 226ms
149 timing auditReport:getReport Completed in 227ms
150 http fetch GET 200 https://registry.npmjs.org/ansi-regex 2ms (from cache)
151 timing metavuln:packument:ansi-regex Completed in 2ms
152 timing metavuln:cache:get:security-advisory:ansi-regex:MnjBQhWFwFkmPMPb2LclMhDfT8OCnRPetf8SCJdoqGvp1Bb0HJtPoZakX9Efg7taRQJTGHclNIupkFKqXo1Dfg== Completed in 3ms
153 timing metavuln:load:security-advisory:ansi-regex:1002401 Completed in 0ms
154 timing metavuln:calculate:security-advisory:ansi-regex:1002401 Completed in 4ms
155 timing metavuln:cache:get:security-advisory:strip-ansi:3+Lck0bTYbnkScUdMxQwoYX9TX29DpNbh0kKo79cpaTAFAkeata/DRpMZSymAH7cxXBroSBEKldl9Ujtv9uEFg== Completed in 2ms
156 http fetch GET 200 https://registry.npmjs.org/strip-ansi 1ms (from cache)
157 timing metavuln:packument:strip-ansi Completed in 2ms
158 timing metavuln:load:security-advisory:strip-ansi:MnjBQhWFwFkmPMPb2LclMhDfT8OCnRPetf8SCJdoqGvp1Bb0HJtPoZakX9Efg7taRQJTGHclNIupkFKqXo1Dfg== Completed in 0ms
159 timing metavuln:calculate:security-advisory:strip-ansi:MnjBQhWFwFkmPMPb2LclMhDfT8OCnRPetf8SCJdoqGvp1Bb0HJtPoZakX9Efg7taRQJTGHclNIupkFKqXo1Dfg== Completed in 2ms
160 http fetch GET 200 https://registry.npmjs.org/string-width 2ms (from cache)
161 timing metavuln:packument:string-width Completed in 2ms
162 timing metavuln:cache:get:security-advisory:string-width:XLdQxI8EM4Vtlga+GCAZa7fuMHS6Ixx/29u7DAAGosOgC/o37GvKCvauVmWp8ye6D2LiGCdy+j/lsFWCmZe9gA== Completed in 2ms
163 timing metavuln:load:security-advisory:string-width:3+Lck0bTYbnkScUdMxQwoYX9TX29DpNbh0kKo79cpaTAFAkeata/DRpMZSymAH7cxXBroSBEKldl9Ujtv9uEFg== Completed in 0ms
164 timing metavuln:calculate:security-advisory:string-width:3+Lck0bTYbnkScUdMxQwoYX9TX29DpNbh0kKo79cpaTAFAkeata/DRpMZSymAH7cxXBroSBEKldl9Ujtv9uEFg== Completed in 2ms
165 http fetch GET 200 https://registry.npmjs.org/cli-truncate 3ms (from cache)
166 timing metavuln:packument:cli-truncate Completed in 4ms
167 timing metavuln:cache:get:security-advisory:cli-truncate:6t7SKPYp576tytoabS5ajF5Ln9gdhfq73l5tmg3KIgF7OcSWZ96x+JANEkNxria2BKchmoGUdTvIHkSQqzuMNQ== Completed in 4ms
168 timing metavuln:load:security-advisory:cli-truncate:XLdQxI8EM4Vtlga+GCAZa7fuMHS6Ixx/29u7DAAGosOgC/o37GvKCvauVmWp8ye6D2LiGCdy+j/lsFWCmZe9gA== Completed in 0ms
169 timing metavuln:calculate:security-advisory:cli-truncate:XLdQxI8EM4Vtlga+GCAZa7fuMHS6Ixx/29u7DAAGosOgC/o37GvKCvauVmWp8ye6D2LiGCdy+j/lsFWCmZe9gA== Completed in 4ms
170 timing metavuln:cache:get:security-advisory:wide-align:/nf6g+9iy/vWmGNQT4IbPdhEbCg8RtuUVsvvbbT66ygOZ2rsv35C3jUigeX6PQS1+K+CjlzORloNS37S77Fv/Q== Completed in 3ms
171 http fetch GET 200 https://registry.npmjs.org/wide-align 3ms (from cache)
172 timing metavuln:packument:wide-align Completed in 3ms
173 timing metavuln:load:security-advisory:wide-align:XLdQxI8EM4Vtlga+GCAZa7fuMHS6Ixx/29u7DAAGosOgC/o37GvKCvauVmWp8ye6D2LiGCdy+j/lsFWCmZe9gA== Completed in 0ms
174 timing metavuln:calculate:security-advisory:wide-align:XLdQxI8EM4Vtlga+GCAZa7fuMHS6Ixx/29u7DAAGosOgC/o37GvKCvauVmWp8ye6D2LiGCdy+j/lsFWCmZe9gA== Completed in 3ms
175 timing auditReport:init Completed in 14ms
176 timing reify:audit Completed in 242ms
177 http fetch GET 304 https://codeload.github.com/sabifa/node-irsdk/tar.gz/9a0796d58891f9de3cee8f6a0a1efab24ba74563 242ms (from cache)
178 timing reify:rollback:createSparse Completed in 15ms
179 timing reify:rollback:retireShallow Completed in 0ms
180 timing command:install Completed in 11807ms
181 verbose stack Error: git dep preparation failed
181 verbose stack     at ChildProcess.<anonymous> (C:\Users\Martin\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
181 verbose stack     at ChildProcess.emit (node:events:390:28)
181 verbose stack     at maybeClose (node:internal/child_process:1062:16)
181 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
182 verbose cwd C:\Users\Martin\Documents\GitHub\motorista
183 verbose Windows_NT 10.0.19043
184 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Martin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "https://github.com/sabifa/node-irsdk"
185 verbose node v17.0.1
186 verbose npm  v7.5.3
187 error code 1
188 error git dep preparation failed
189 error command C:\Program Files\nodejs\node.exe C:\Users\Martin\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\Martin\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
190 error > node-irsdk@2.1.6 install
190 error > prebuild-install || node-gyp rebuild
190 error
190 error Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
190 error   IrSdkNodeBindings.cpp
190 error   IrSdkCommand.cpp
190 error   IRSDKWrapper.cpp
190 error   IrSdkBindingHelpers.cpp
190 error   win_delay_load_hook.cc
190 error c:\users\martin\appdata\local\npm-cache\_cacache\tmp\git-clone-7601f52b\src\cpp\irsdknodebindings.h(39): error C2660: 'node::AtExit': function does not take 1 arguments (compiling source file ..\src\cpp\IrSdkNodeBindings.cpp) [C:\Users\Martin\AppData\Local\npm-cache\_cacache\tmp\git-clone-7601f52b\build\IrSdkNodeBindings.vcxproj]
190 error   c:\users\martin\.node-gyp\17.0.1\include\node\node.h(935): note: see declaration of 'node::AtExit' (compiling source file ..\src\cpp\IrSdkNodeBindings.cpp)
191 error npm WARN using --force Recommended protections disabled.
191 error gyp info it worked if it ends with ok
191 error gyp info using node-gyp@3.8.0
191 error gyp info using node@17.0.1 | win32 | x64
191 error (node:14404) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
191 error (Use `node --trace-deprecation ...` to show where the warning was created)
191 error gyp info spawn C:\Users\Martin\.windows-build-tools\python27\python.exe
191 error gyp info spawn args [
191 error gyp info spawn args   'C:\\Users\\Martin\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone-7601f52b\\node_modules\\node-gyp\\gyp\\gyp_main.py',
191 error gyp info spawn args   'binding.gyp',
191 error gyp info spawn args   '-f',
191 error gyp info spawn args   'msvs',
191 error gyp info spawn args   '-G',
191 error gyp info spawn args   'msvs_version=2015',
191 error gyp info spawn args   '-I',
191 error gyp info spawn args   'C:\\Users\\Martin\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone-7601f52b\\build\\config.gypi',
191 error gyp info spawn args   '-I',
191 error gyp info spawn args   'C:\\Users\\Martin\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone-7601f52b\\node_modules\\node-gyp\\addon.gypi',
191 error gyp info spawn args   '-I',
191 error gyp info spawn args   'C:\\Users\\Martin\\.node-gyp\\17.0.1\\include\\node\\common.gypi',
191 error gyp info spawn args   '-Dlibrary=shared_library',
191 error gyp info spawn args   '-Dvisibility=default',
191 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Martin\\.node-gyp\\17.0.1',
191 error gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Martin\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone-7601f52b\\node_modules\\node-gyp',
191 error gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Martin\\.node-gyp\\17.0.1\\<(target_arch)\\node.lib',
191 error gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Martin\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone-7601f52b',
191 error gyp info spawn args   '-Dnode_engine=v8',
191 error gyp info spawn args   '--depth=.',
191 error gyp info spawn args   '--no-parallel',
191 error gyp info spawn args   '--generator-output',
191 error gyp info spawn args   'C:\\Users\\Martin\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone-7601f52b\\build',
191 error gyp info spawn args   '-Goutput_dir=.'
191 error gyp info spawn args ]
191 error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
191 error gyp info spawn args [
191 error gyp info spawn args   'build/binding.sln',
191 error gyp info spawn args   '/clp:Verbosity=minimal',
191 error gyp info spawn args   '/nologo',
191 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
191 error gyp info spawn args ]
191 error gyp ERR! build error
191 error gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
191 error gyp ERR! stack     at ChildProcess.onExit (C:\Users\Martin\AppData\Local\npm-cache\_cacache\tmp\git-clone-7601f52b\node_modules\node-gyp\lib\build.js:262:23)
191 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
191 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
191 error gyp ERR! System Windows_NT 10.0.19043
191 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Martin\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone-7601f52b\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
191 error gyp ERR! cwd C:\Users\Martin\AppData\Local\npm-cache\_cacache\tmp\git-clone-7601f52b
191 error gyp ERR! node -v v17.0.1
191 error gyp ERR! node-gyp -v v3.8.0
191 error gyp ERR! not ok
191 error npm ERR! code 1
191 error npm ERR! path C:\Users\Martin\AppData\Local\npm-cache\_cacache\tmp\git-clone-7601f52b
191 error npm ERR! command failed
191 error npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
191 error
191 error npm ERR! A complete log of this run can be found in:
191 error npm ERR!     C:\Users\Martin\AppData\Local\npm-cache\_logs\2021-10-31T13_30_02_459Z-debug.log
192 verbose exit 1`

Would be cool, if somebody with more expertise than me might figure out, what's going on.
